platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MappyQuickStart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MappyQuickStart
  pod 'Mappy' # Elegant and composable interface for mapping, geocoding, and routing.

end
