platform :ios, '14.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MappyQuickStart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MappyQuickStart
  pod 'Mappy', '0.4.9' # Elegant and composable interface for mapping, geocoding, and routing.

end
